title: AGseminar
author: Xuande Liu
email: xuande.liu@stonybrook.edu
description: > # this means to ignore newlines until "show_exerpts:"
  This is the website for the algebraic geometry seminar at stonybrook university.
show_excerpts: true # set to true to show excerpts on the homepage

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass

permalink: /posts/:title/
texture:
  title: Algebraic Geometry Reading Seminar: Intersection Theory
  tagline: Stony Brook University
  date_format: "%b %-d, %Y"
  style: black
  showNav: false
  showPicker: true

#   generate social links in footer
#   social_links:
#     Email: xuande.liu@stonybrook.edu
#     Email: Zhengze.Xin@stonybrook.edu
#     github:  Xuande Liu
#     rss: rss
 

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
# theme: texture

plugins:
  - jekyll-seo-tag
#  - jekyll-feed
